// ignore_for_file: public_member_api_docs, sort_constructors_first
/// Generated by AssetsRefGenerator on 2023/11/07
class Res {
  static const _icon = "assets/icon/";
  static const _icons = "assets/icons/";
  static const _images = "assets/images/";

  static const String splash_user = _images + "splash_user.json";
  static const String icon = _icon + "icon.png";
  static const String img = _icon + "img.png";
  static const String ios_icon_app = _icon + "ios_icon_app.png";
  static const String loading_summary = _images + "loading_summary.png";
  static const String head_splash = _images + "head_splash.png";
  static const String bot_splash = _images + "bot_splash.svg";
  static const String main_logo = _images + "main_logo.svg";
  static const String logo_smart_village = _icons  + "logo_smartvillage.png";
  
  // icon for register page
  static const String icon_medical_staff = _icons + "icon_medical_staff.svg";
  static const String icon_elderly = _icons + "icon_elderly.svg";
  static const String icon_buckler = _icons + "icon_buckler.svg";
  static const String icon_cached = _icons + "icon_cached.svg";
  static const String image_check_successful = _images + "image_check_successful.svg";
  static const String icon_warning_outline = _icons + "icon_warning_outline.svg";
  static const String file_pdf = _images + "file_pdf.png";

}
